# From: hack4impact-uiuc/mern-template
name: api

on: push

defaults:
  run:
    working-directory: ./api

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7.0

      - name: Setup env
        run: |
          echo .env.example > .env

      - name: Run test
        run: yarn test
