# From: hack4impact-uiuc/mern-template
name: api

on: push

defaults:
  run:
    working-directory: ./api

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: api/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: yarn

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run linter
        env:
            MONGODB_URI: mongodb://localhost:27017/ntc-server
        run: yarn test
