name: client

on: push

defaults:
  run:
    working-directory: ./client

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: npm i

      - name: Check formatting
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: npm i

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build
